import type {
  ArcRotateCamera,
  EngineContext,
  SceneContext,
} from "@babylonjs/lite";
import type { LiteViewer } from "./LiteViewer.js";

/**
 * Model input accepted by {@link LiteViewer.loadModel}.
 *
 * Use a string for remote or application-hosted glTF/GLB assets. Use `Blob` or
 * `ArrayBuffer` for locally selected files.
 */
export type LiteViewerSource = string | Blob | ArrayBuffer;

/**
 * Startup and lifecycle options for {@link LiteViewer}.
 */
export type LiteViewerOptions = {
  /**
   * Optional model to load during initialization.
   */
  source?: LiteViewerSource;

  /**
   * Controls whether the viewer adds a default hemispheric light.
   *
   * Defaults to `true`.
   */
  light?: boolean;

  /**
   * Optional environment texture URL.
   *
   * The viewer asks Babylon Lite to load this environment with the packaged
   * default BRDF LUT texture.
   */
  environment?: string;

  /**
   * Skips the skybox generated by Babylon Lite's environment loader.
   */
  skipSkybox?: boolean;

  /**
   * Skips the ground generated by Babylon Lite's environment loader.
   *
   * Defaults to `true`.
   */
  skipGround?: boolean;

  /**
   * Controls whether the render loop starts automatically after initialization.
   *
   * Defaults to `true`. Set this to `false` when you want to call
   * {@link LiteViewer.start} manually.
   */
  autoStart?: boolean;

  /**
   * Called after the engine, scene, and camera are ready.
   */
  onInitialized?: (details: LiteViewerDetails) => void;

  /**
   * Called after a model has been loaded and added to the scene.
   */
  onLoaded?: (details: LiteViewerDetails) => void;

  /**
   * Called when initialization, model loading, or environment loading fails.
   */
  onError?: (error: unknown) => void;
};

/**
 * Handles returned after viewer initialization.
 */
export type LiteViewerDetails = {
  /**
   * The high-level viewer instance.
   */
  viewer: LiteViewer;

  /**
   * Canvas element used for rendering and camera controls.
   */
  canvas: HTMLCanvasElement;

  /**
   * Babylon Lite engine context.
   */
  engine: EngineContext;

  /**
   * Active Babylon Lite scene context.
   */
  scene: SceneContext;

  /**
   * Active ArcRotate camera created by Babylon Lite.
   */
  camera: ArcRotateCamera;
};

/**
 * Internal lifecycle state used by the viewer.
 *
 * This type is exported for diagnostics and advanced integrations, but ordinary
 * applications usually do not need it.
 */
export type ViewerState =
  | "idle"
  | "initializing"
  | "ready"
  | "loading"
  | "loaded"
  | "error"
  | "disposed";
